---
providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./
    enforce_order: False
  dnsimple:
    class: octodns.provider.dnsimple.DnsimpleProvider
    token: env/DNSIMPLE_API_KEY
    account: env/DNSIMPLE_ACCOUNT_NUMBER

zones:
  hack.af.:
    sources:
      - config
    targets:
      - dnsimple
